version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test
      - POSTGRES_USER=apiservices
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
